name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    env:
      CC:   gcc
      MAKE: make
      LDD:  ldd

    steps:
    - uses: actions/checkout@v4

#    - name: Install neofetch
#      run: sudo apt install -y neofetch

    # ここから共通 ----------
    - name: version - date, uname, $CC, $MAKE
      run: |
        date
        uname -a
        echo "----------"
        $CC --version
        $MAKE --version

    - name: run rls debug
      run: |
        $MAKE clean debug
        ./rls -always

    - name: run rls md5
      run: |
        $MAKE clean md5
        ./rls -always -fmogcdw5NkPle -alr

    - name: $MAKE, $LDD
      run: |
        $MAKE clean wrapper count
        echo "----------"
        $MAKE clean
        $MAKE
        echo $LDD ./rls
        $LDD ./rls

    - name: rls version, help
      run: |
        ./rls --version
        echo "----------"
        ./rls --help

    - name: run rls
      run: |
        ./rls -alr -TB\[ -TE\]
        echo "----------"
        ./rls -alr -always
        echo "----------"
        ./rls -TB\[ -TE\]
        echo "----------"
        ./rls -always


  ## make がダメそう、ldd 無さそうなので一旦コンパイルだけ
  build_macos:
    runs-on: macos-latest
    env:
      CC:   /usr/local/bin/gcc
      MAKE: gmake
      LDD:  otool -L
    steps:
    - uses: actions/checkout@v4

    ## インストールしないと clang が使用される
    - name: install gcc
      uses: Dup4/actions-setup-gcc@v1
#      with:
#        version: latest

    - name: Install gmake, openssl
      run: |
        brew install make
        brew install openssl

    # ここから共通 ----------
    - name: version - date, uname, $CC, $MAKE
      run: |
        date
        uname -a
        echo "----------"
        $CC --version
        $MAKE --version

    - name: run rls debug
      run: |
        $MAKE clean debug
        ./rls -always

    - name: run rls md5
      run: |
        $MAKE clean md5
        export OPENSSL_DIR=$(brew --prefix openssl@3)
        gcc -I$OPENSSL_DIR/include -L$OPENSSL_DIR/lib -DMD5 rls.c -lssl -lcrypto -o rls
        ./rls -always -fmogcdw5NkPle -alr

    - name: $MAKE, $LDD
      run: |
        $MAKE clean wrapper count
        echo "----------"
        $MAKE clean
        $MAKE
        echo $LDD ./rls
        $LDD ./rls

    - name: rls version, help
      run: |
        ./rls --version
        echo "----------"
        ./rls --help

    - name: run rls
      run: |
        ./rls -alr -TB\[ -TE\]
        echo "----------"
        ./rls -alr -always
        echo "----------"
        ./rls -TB\[ -TE\]
        echo "----------"
        ./rls -always
