name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

#    - name: Install neofetch
#      run: sudo apt install -y neofetch

    - name: ubuntu version - date, uname, gcc, make
      run: |
        echo "----------"
        date
        uname -a
        echo "----------"
        gcc --version
        make --version

    - name: run rls debug
      run: |
        make clean debug
        ./rls -always

    - name: make, ldd
      run: |
        make clean wrapper count debug
        echo "----------"
        make clean
        make
        echo ldd ./rls
        ldd ./rls

    - name: rls version, help
      run: |
        ./rls --version
        echo "----------"
        ./rls --help

    - name: run rls
      run: |
        ./rls -alr -TB\[ -TE\]
        echo "----------"
        ./rls -alr -always
        echo "----------"
        ./rls -TB\[ -TE\]
        echo "----------"
        ./rls -always


  ## make がダメそう、ldd 無さそうなので一旦コンパイルだけ
  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: install gcc
      uses: Dup4/actions-setup-gcc@v1
      with:
        version: latest

    - name: macos version - date, uname, gcc, make
      run: |
        date
        uname -a
        echo "----------"
        gcc --version
        make --version

    - name: run rls debug
      run: |
        rm -f ./rls
        gcc -DDEBUG -g3 -O0 -Wall -Wextra rls.c -o rls
        ./rls -alr -always

    - name: build rls
      run: |
        rm -f ./rls
        gcc -O3 -pipe rls.c -o rls

    - name: rls version, help
      run: |
        ./rls --version
        echo "----------"
        ./rls --help

    - name: run rls
      run: |
        ./rls -alr -TB\[ -TE\]
        echo "----------"
        ./rls -alr -always
        echo "----------"
        ./rls -TB\[ -TE\]
        echo "----------"
        ./rls -always
